name: Publish

on:
  push:
    branches: [ src ]
  pull_request:
    branches: [ src ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install

    - name: Clean up
      run: rm -rf node_modules/.cache

    - name: Build
      run: npm run build

    - name: Commit
      run: |
        git config user.name "SynZhang"
        git config user.email "zeyanzhang.china@gmail.com"
        touch out/.nojekyll
        git add out/
        git commit -m "chore: deploy"
        git branch master HEAD
        git filter-branch --prune-empty --subdirectory-filter out -- master
        git push origin master -f
        git push origin